[2025-07-01T13:49:01.792+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T13:49:01.806+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: grazing_detection_streaming_cluster.submit_grazing_detector_job manual__2025-07-01T13:49:01.181373+00:00 [queued]>
[2025-07-01T13:49:01.808+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: grazing_detection_streaming_cluster.submit_grazing_detector_job manual__2025-07-01T13:49:01.181373+00:00 [queued]>
[2025-07-01T13:49:01.808+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T13:49:01.812+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): submit_grazing_detector_job> on 2025-07-01 13:49:01.181373+00:00
[2025-07-01T13:49:01.816+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=224) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T13:49:01.815+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'grazing_detection_streaming_cluster', 'submit_grazing_detector_job', 'manual__2025-07-01T13:49:01.181373+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/grazing_dag.py', '--cfg-path', '/tmp/tmptusibxpn']
[2025-07-01T13:49:01.817+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask submit_grazing_detector_job
[2025-07-01T13:49:01.817+0000] {standard_task_runner.py:63} INFO - Started process 225 to run task
[2025-07-01T13:49:01.840+0000] {task_command.py:426} INFO - Running <TaskInstance: grazing_detection_streaming_cluster.submit_grazing_detector_job manual__2025-07-01T13:49:01.181373+00:00 [running]> on host 67cfbb7bbf7c
[2025-07-01T13:49:01.874+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='grazing_detection_streaming_cluster' AIRFLOW_CTX_TASK_ID='submit_grazing_detector_job' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T13:49:01.181373+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-01T13:49:01.181373+00:00'
[2025-07-01T13:49:01.875+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T13:49:01.908+0000] {docker.py:359} INFO - Starting docker container from image bitnami/spark:3.5
[2025-07-01T13:49:01.913+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T13:49:01.913+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.48/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 391, in _run_image_with_mounts
    self.container = self.cli.create_container(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 440, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.48/containers/create: Bad Request ("invalid mount config for type "bind": invalid mount path: '$(pwd)/airflow/spark_jobs' mount path must be absolute")
[2025-07-01T13:49:01.918+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=grazing_detection_streaming_cluster, task_id=submit_grazing_detector_job, run_id=manual__2025-07-01T13:49:01.181373+00:00, execution_date=20250701T134901, start_date=20250701T134901, end_date=20250701T134901
[2025-07-01T13:49:01.923+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task submit_grazing_detector_job (400 Client Error for http+docker://localhost/v1.48/containers/create: Bad Request ("invalid mount config for type "bind": invalid mount path: '$(pwd)/airflow/spark_jobs' mount path must be absolute"); 225)
[2025-07-01T13:49:01.959+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-01T13:49:01.967+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T13:49:01.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
